### ISSUE TITLE
[website] Logo is huge in Safari

### ISSUE THREAD

**Issue by LeaVerou** [madatajs/madata#28]
<img width="939" alt="image" src="https://user-images.githubusercontent.com/175836/216452673-6b0fed76-a647-4bac-9c6f-21083fde877b.png">

**Comment by DmitrySharabin** [comment]
We lost the changes we made earlier, so this needs to be re-opened.

**Comment by DmitrySharabin** [comment]
I researched a bit, and it looks like the issue we face might be related to a problem with `grid-template-columns: auto` and an SVG inside it: https://stackoverflow.com/questions/63210102/css-grid-auto-width-doesnt-work-with-svg.

In our CSS, the logo is exactly inside a column with the `auto` width.

**Comment by LeaVerou** [comment]
This seems to have been fixed, I can't reproduce it in Safari 17.4 at least.
