### ISSUE TITLE
Rename `Backend.create()` to `Backend.from()`

### ISSUE THREAD

**Issue by LeaVerou** [madatajs/madata#39]
`Backend.create()` sounds like it's *creating* something, e.g. a GitHub repo, whereas it merely is a factory method for creating a suitable `Backend` subclass. `Backend.from()` is more clear.

Any objections?

**Comment by karger** [comment]
Maybe createInstance or createFrom?

**Comment by LeaVerou** [comment]
Yikes. That's not the direction JS APIs are heading, it's kind of reminiscent of Java.
