### ISSUE TITLE
Some ESLint rules that might help us and future contributors to maintain the coding style we follow

### ISSUE THREAD

**Issue by DmitrySharabin** [madatajs/madata#45]
Today, I decided to remove the Prettier extension from VS Code and switch to [ESLint](https://marketplace.visualstudio.com/items?itemName=dbaeumer.vscode-eslint) and make it the default formatter for JS files. ESLint is much more configurable and supports rules we can apply to support our coding style.

It looks like this configuration (`.eslintrc.js` 👇) supports most (if not all) rules we need. I installed ESLint globally and enabled these rules by default (since we use the same rules in many other projects, like, e.g., [Mavo](https://mavo.io/)). But I think we can do it on separate repo by adding ESLint as a dev dependency. For me, it's `"eslint": "^8.36.0"`.

```js
module.exports = {
	"env": {
		"browser": true,
		"es2021": true,
		"node": true
	},
	"extends": "eslint:recommended",
	"overrides": [
	],
	"parserOptions": {
		"ecmaVersion": "latest",
		"sourceType": "module"
	},
	"rules": {
		"indent": [
			"error",
			"tab",
			{ "outerIIFEBody": 0 }
		],
		"linebreak-style": [
			"error",
			"unix"
		],
		"quotes": [
			"error",
			"double",
			{ "allowTemplateLiterals": true }
		],
		"curly": "error",
		"semi": [
			"error",
			"always"
		],
		"brace-style": [
			"error",
			"stroustrup",
			{ "allowSingleLine": true }
		],
		"space-before-function-paren": [
			"error",
			"always"
		],
		"no-multiple-empty-lines": [
			"error",
			{ "max": 1, "maxEOF": 0 }
		],
		"no-empty": [
			"error",
			{ "allowEmptyCatch": true }
		]
	}
};
```

Now, I can finally hit `CMD + S`, and nothing is broken, and the issues (like missing semicolons, etc.) are fixed. Yay! 🎉

**Comment by LeaVerou** [comment]
Oh yeah, we should definitely have an ESLint file! Can you send a PR?
