### ISSUE TITLE
Issues with `file` and `ref` in file-based backends

### ISSUE THREAD

**Issue by DmitrySharabin** [madatajs/madata#72]
In #62, we moved from the `file` concept to `ref`. However, since `file` makes more sense than `ref` in file-based backends (Github, Dropbox, and Google Drive), we still use `file` as the parameter name with those backends.

Unfortunately, that decision led us to regressions.

For example, here we call a backend's `put` method and pass `ref` inside the dictionary:

https://github.com/madatajs/madata/blob/ee50a7e3455e64d6523a19d53b207ab5686c7cde/src/backend.js#L232

However, here we expect `file`, not `ref`:

https://github.com/madatajs/madata/blob/ee50a7e3455e64d6523a19d53b207ab5686c7cde/backends/github/file/github-file.js#L86

We can fix it by renaming `ref` to `file` (to continue using `file` inside `put()`), like so:

```diff
- async put (data, {file, isEncoded} = {}) { 
+ async put (data, {ref: file, isEncoded} = {}) { 
```

But later on in this method, we need to call `stringify()` that has the following signature (mind `ref`):

https://github.com/madatajs/madata/blob/ee50a7e3455e64d6523a19d53b207ab5686c7cde/src/backend.js#L73

So, we need to change the following code:

https://github.com/madatajs/madata/blob/ee50a7e3455e64d6523a19d53b207ab5686c7cde/backends/github/file/github-file.js#L87

```diff
- const serialized = await this.stringify(data, {file});
+ const serialized = await this.stringify(data, {ref: file});
```

Even though we might perform all the changes to fix the regressions, I wonder whether we should continue using `file` (and remember all the nuances) or if it makes more sense to use `ref` all over the codebase. 🤔

What do you think?

**Comment by LeaVerou** [comment]
Yeah I think it makes sense to use `ref` all over.

**Comment by DmitrySharabin** [comment]
Will fix it then. Thanks.
