### ISSUE TITLE
Add path aliases to simplify imports

### ISSUE THREAD

**Issue by DmitrySharabin** [madatajs/madata#77]
Our codebase has some very complex imports that are not easy to read but also challenging to write (even with the help of an IDE).

Here are some examples:

https://github.com/madatajs/madata/blob/38f6203127c257603048a2726c9e1527c3ac2f40/formats/csv/index.js#L1-L2

https://github.com/madatajs/madata/blob/38f6203127c257603048a2726c9e1527c3ac2f40/backends/basic/element.js#L1-L2

https://github.com/madatajs/madata/blob/38f6203127c257603048a2726c9e1527c3ac2f40/components/auth/index.js#L1

And my favorite one: 😅

https://github.com/madatajs/madata/blob/38f6203127c257603048a2726c9e1527c3ac2f40/backends/github/file/github-file.js#L2-L3

There is [a native way](https://betterprogramming.pub/the-native-way-to-configure-path-aliases-in-frontend-projects-5db70f19a6e0#2d0d) to make those paths more readable and maintainable with [subpath imports](https://nodejs.org/api/packages.html#subpath-imports).

With subpath imports, we'll get (no matter how deep the file importing another module is nested):

```diff
- import Format from "../../src/format.js";
+ import Format from "#src/format.js";

- import { parse, stringify } from "../../lib/csv/dist/esm/sync.js";
+ import { parse, stringify } from "#lib/csv/dist/esm/sync.js";

- import hooks from "../../../src/hooks.js";
+ import hooks from "#src/hooks.js";
```

To make this work, we need to add these lines to `package.json`:

```json
"imports": {
  "#src/*": "./src/*",
  "#backends/*": "./backends/*",
  "#formats/*": "./formats/*",
  "#lib/*": "./lib/*"
}
```

For code navigation to work in an IDE, we should also configure path aliases in the `tsconfig.json` file (that we already use to generate the API documentation):

```json
"baseUrl": "./",
"paths": {
	"#src/*": ["./src/*"],
	"#backends/*": ["./backends/*"],
	"#formats/*": ["./formats/*"],
	"#lib/*": ["./lib/*"],
}
```

I already played with it a bit—it works like a charm. I'm ready to submit a PR if we need this feature.

**Comment by LeaVerou** [comment]
Those are not supported in browsers. :(
